version: "3"

services:
    front:
        build: ./front      
        ports:
            - '3000:3000'
        volumes:
            - ./front:/usr/src/app
            - /usr/src/app/node_modules

    server:
        build: ./server
        ports:
            - "3333:3333"
        environment:
            - DATABASE_URL=mongodb://mongo/code00
            - PORT=3333
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
    mongo:
        image: mongo:latest
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
volumes:
  mongodata:
